server.port=8080
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable automatic service discovery routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# This allows routing like: http://localhost:8080/user-service/api/auth/register
# It will automatically find the service registered in Eureka and route to it

